name: Coreferee Matrix Test
on: 
  workflow_dispatch:
  pull_request:

jobs:
  test-coreferee:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-20.04]
        python_version: ['3.11']
        spacy_version: ['3.8.0']
        click_version: ['8.4.1']
        include:
          - os: 'ubuntu-20.04'
            python_version: '3.11'
            spacy_version: '3.8.0'
            click_version: '8.4.1'
          - os: 'windows-latest'
            python_version: '3.11'
            spacy_version: '3.8.0'
            click_version: '8.4.1'
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3

    - name: Initialize Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python_version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install spacy==${{ matrix.spacy_version }} pytest
        
        # see https://github.com/explosion/spaCy/issues/10564
        pip uninstall click -y
        pip install "click==${{ matrix.click_version }}"


    - name: Install spaCy models
      run: |
        python -m spacy download en_core_web_sm

        
    - name: Install Coreferee
      run: |
        cd ${{ github.workspace }}
        pip install .
        python -m coreferee install en

    - name: Test Coreferee 
      run: |
        python -m pytest tests/common
        python -m pytest tests/en

